build site:
  image: node:6
  stage: build
  script:
    - cd VoX-Wallet/web
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - VoX-Wallet/web/dist

unit test:
  image: node:6
  stage: test
  script:
    - cd VoX-Wallet/web
    - npm install --progress=false
    - npm run unit

deploy:
  stage: deploy
  script:
    - cd VoX-Wallet/web/dist
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
