language: node_js
node_js:
 - "8.9.4"
branches:
 only:
 - master
before_script:
 - cd voxwallet
 - npm install -g ionic cordova
 - npm install -g @angular/cli
script:
 - npm i
 - ionic build --prod --aot
deploy:
 provider: firebase
 token: 
   secure: $FIREBASE_TOKEN
 local_dir: voxwallet/www
