language: node_js
node_js:
 - "8.9.4"
branches:
 only:
 - master
before_script:
 - cd voxwallet
 - npm install -g ionic cordova
 - npm install -g @angular/cli
script:
 - npm i
 - ionic cordova build browser
deploy:
 provider: pages
 skip-cleanup: true
 keep-history: true
 on:
   branch: master
 local_dir: www
